// File generated by `flutterfire configure` (Android) + manually extended for
// iOS on 2026-04-29 from ios/Runner/GoogleService-Info.plist values, since
// re-running `flutterfire configure` would risk re-introducing
// firebase_analytics + firebase_crashlytics SDK references that we
// deliberately strip for the iOS Kids Category build (PLAN.md 1A-3, 1P-1,
// 1P-3). Edit by hand if Firebase project values change.
//
// CYCLE-PROTECT: This file contains iOS-conditional code. Do not auto-remove
// the iOS branch without verifying iOS Simulator launch — `Firebase.initializeApp`
// throws UnsupportedError if the platform is missing.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPW2YvhSRZt_WV2dpJo9ol5TtHPspTXlY',
    appId: '1:722700244830:android:4c853fb0ff20d0bf07a1cf',
    messagingSenderId: '722700244830',
    projectId: 'brush-quest',
    storageBucket: 'brush-quest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhXpED7N_pFRon9izzLJdw4eeK026FrHk',
    appId: '1:722700244830:ios:edc34bfb6082ebb107a1cf',
    messagingSenderId: '722700244830',
    projectId: 'brush-quest',
    storageBucket: 'brush-quest.firebasestorage.app',
    iosClientId:
        '722700244830-reuomeurm7s9rh3ue5b2fkthb7gqnglk.apps.googleusercontent.com',
    iosBundleId: 'com.brushquest.brushQuest',
  );
}
